# Generated by Django 5.2.8 on 2026-02-02 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('longitud_km', models.FloatField()),
                ('vueltas', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('escuderia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.escuderia')),
            ],
            options={
                'unique_together': {('nombre', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piloto')),
            ],
            options={
                'unique_together': {('user', 'piloto')},
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.circuito')),
                ('primero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_primero', to='core.piloto')),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_segundo', to='core.piloto')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_tercero', to='core.piloto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'circuito')},
            },
        ),
    ]
