# Generated by Django 5.2.8 on 2026-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuderia',
            name='color',
            field=models.CharField(default='#333333', help_text='Ej: #FF0000', max_length=7),
        ),
        migrations.AddField(
            model_name='piloto',
            name='codigo_pais',
            field=models.CharField(default='xx', help_text='Código ISO de 2 letras (es, gb, fr...)', max_length=2),
        ),
    ]
