# Generated by Django 5.2.8 on 2026-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escuderia_color_piloto_codigo_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='codigo_pais',
            field=models.CharField(default='xx', max_length=2),
        ),
    ]
